fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        files: \.py$
        stages: [commit]
        language: system
        entry: isort .
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black .
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8
        types: [python]

      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pylint --fail-under=9.99 apps
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        stages: [commit]
        language: system
        entry: bandit --ini .bandit
        types: [python]

      - id: safety
        name: safety
        stages: [commit]
        language: system
        entry: safety check -r requirements.txt -r requirements-dev.txt --full-report
        pass_filenames: false
